ProjetoStefanini/Models/Custumer.cs
using ProjetoStefanini.Helpers.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;


namespace ProjetoStefanini.Models
{
    public class Custumer
    {
        [Key]
        public int Id { get; set; }
        public string Classification { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public EGender Gender { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        [DataType(DataType.Date, ErrorMessage = "Data in invalid format!")]
        public DateTime LastPurchase { get; set; }
        [DataType(DataType.Date, ErrorMessage = "Data in invalid format!")]
        public DateTime Until { get; set; }
        public string Seller { get; set; }

    }
}

ProjetoStefanini/Controllers/CustumerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ProjetoStefanini.Models;
using ProjetoStefanini.Helpers.Enums;

namespace ProjetoStefanini.Controllers
{
    [Authorize]
    public class CustumerController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        #region INDEX
        // GET: Custumer
        public ActionResult Index(String searchString_)
        {
            //IEnumerable<ViewModelCustumer> registros = Enumerable.Empty<ViewModelCustumer>();
            //registros = GetDados(searchString_);

            if (User.IsInRole("Administrator"))
                return View(db.Custumers.ToList());
            else
                return View(db.Custumers.Where(x => x.Seller == User.Identity.Name).ToList());
        }
        #endregion

        #region DETAILS
        // GET: Custumer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Custumer custumer = db.Custumers.Find(id);
            if (custumer == null)
            {
                return HttpNotFound();
            }
            return View(custumer);
        }
        #endregion

        #region CREATE
        // GET: Custumer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Custumer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Classification,Name,Phone,Gender,City,Region,LastPurchase,Until,Seller")] Custumer custumer)
        {
            if (ModelState.IsValid)
            {
                custumer.Seller = User.Identity.Name;
                db.Custumers.Add(custumer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(custumer);
        }
        #endregion

        #region EDIT
        // GET: Custumer/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Custumer custumer = db.Custumers.Find(id);
            if (custumer == null)
            {
                return HttpNotFound();
            }
            return View(custumer);
        }

        // POST: Custumer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Classification,Name,Phone,Gender,City,Region,LastPurchase,Until,Seller")] Custumer custumer)
        {
            if (ModelState.IsValid)
            {
                custumer.Seller = User.Identity.Name;
                db.Entry(custumer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(custumer);
        }
        #endregion

        #region DELETE
        // GET: Custumer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Custumer custumer = db.Custumers.Find(id);
            if (custumer == null)
            {
                return HttpNotFound();
            }
            return View(custumer);
        }

        // POST: Custumer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Custumer custumer = db.Custumers.Find(id);
            db.Custumers.Remove(custumer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        #endregion

        #region DISPOSE
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion

        #region IMPLEMENTAÇÃO NÃO FINALIZADA
        private IList<ViewModelCustumer> GetDados(ParametrosTelaCustumer searchModel)
        {
            db.Configuration.ProxyCreationEnabled = false;

            try
            {
                var registro = CarregaCustumer(db);
                registro = FiltrarCampos(searchModel, registro);

                return TransformerCustumerView(registro);
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        private IList<ViewModelCustumer> TransformerCustumerView(IQueryable<ViewModelCustumer> custumer)
        {
            var registros = new List<ViewModelCustumer>();
            if (custumer != null)
                foreach (var item in custumer)
                {
                    var registro = new ViewModelCustumer();

                    registro.Classification = item.Classification;
                    registro.City = item.City;
                    registro.Seller = item.Seller;
                    registro.Region = item.Region;
                    registro.Gender = item.Gender;
                    registro.Phone = item.Phone;
                    registro.Name = item.Name;
                    registro.LastPurchase = item.LastPurchase;
                    registro.Until = item.Until;
                    registros.Add(registro);
                }

            return registros;
        }

        private IQueryable<ViewModelCustumer> CarregaCustumer(ApplicationDbContext db)
        {
            var registro = db.Custumers
               .Select(c => new ViewModelCustumer
               {
                   Classification = c.Classification,
                   City = c.City,
                   Seller = c.Seller,
                   Region = c.Region,
                   Gender = c.Gender,
                   Phone = c.Phone,
                   Name = c.Name,
                   LastPurchase = c.LastPurchase,
                   Until = c.Until
               });

            return registro;
        }


        private IQueryable<ViewModelCustumer> FiltrarCampos(ParametrosTelaCustumer searchModel, IQueryable<ViewModelCustumer> registros)
        {
            if (searchModel.Classification != null)
            {
                registros = registros.Where(x => x.Classification == searchModel.Classification);
            }
            if (searchModel.City != null)
            {
                registros = registros.Where(x => x.City == searchModel.City);
            }
            if (!String.IsNullOrEmpty(searchModel.Name))
            {
                registros = registros.Where(c => c.Name.Contains(searchModel.Name));
            }
            if (!String.IsNullOrEmpty(searchModel.Phone))
            {
                registros = registros.Where(c => c.Phone == searchModel.Phone);
            }
            if (!String.IsNullOrEmpty(searchModel.Region))
            {
                registros = registros.Where(c => c.Region.Contains(searchModel.Region));
            }
            if (!String.IsNullOrEmpty(searchModel.Seller))
            {
                registros = registros.Where(c => c.Seller == searchModel.Seller);
            }
            return registros.AsQueryable();
        }

        #endregion
    }

    #region IMPLEMENTAÇÃO NÃO FINALIZADA
    public class ParametrosTelaCustumer
    {
        public string Classification { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public EGender Gender { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public DateTime LastPurchase { get; set; }
        public DateTime Until { get; set; }
        public string Seller { get; set; }
    }

    public class ViewModelCustumer
    {
        public string Classification { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public EGender Gender { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public DateTime LastPurchase { get; set; }
        public DateTime Until { get; set; }
        public string Seller { get; set; }
    }
    #endregion
}

ProjetoStefanini/Views/Custumer/Create.cshtml
@model ProjetoStefanini.Models.Custumer

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Custumer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Classification, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Classification, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Classification, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Gender, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Region, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Region, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Region, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastPurchase, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastPurchase, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastPurchase, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Until, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Until, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Until, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetoStefanini/Views/Custumer/Delete.cshtml
@model ProjetoStefanini.Models.Custumer

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Custumer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Classification)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Classification)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Region)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Region)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastPurchase)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastPurchase)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Until)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Until)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProjetoStefanini/Views/Custumer/Details.cshtml
@model ProjetoStefanini.Models.Custumer

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Custumer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Classification)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Classification)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Region)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Region)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastPurchase)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastPurchase)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Until)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Until)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProjetoStefanini/Views/Custumer/Edit.cshtml
@model ProjetoStefanini.Models.Custumer

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Custumer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Classification, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Classification, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Classification, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Gender, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Region, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Region, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Region, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastPurchase, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastPurchase, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastPurchase, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Until, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Until, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Until, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetoStefanini/Views/Custumer/Index.cshtml
@model IEnumerable<ProjetoStefanini.Models.Custumer>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>


@*<h3>Filters</h3>*@

<div id="SearchContainer" class="collapse in" aria-expanded="true">
    @*<fieldset>

        @using (Html.BeginForm("Index", "Custumer", FormMethod.Get, new { role = "form" }))
        {

            <div class="input-group">
                @Html.TextBox("searchString_", null, new { @class = "input-sm form-control", placeholder = "Classification" })
                
                <span class="input-group-btn">
                    <input type="submit" class="btn btn-sm btn-primary" value="Buscar">
                </span>
            </div>
            <br />
            
            <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span> Pesquisar</button>
            <button type="button" id="ClearSearch" class="btn btn-primary"><span class="glyphicon glyphicon-remove-circle"></span> Limpar Filtros</button>

        }

        
        <br />
        <br />
        <p>
            
        </p>
    </fieldset>*@
</div>
<hr />



<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Classification)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Region)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastPurchase)
        </th>

        @{
            if (User.IsInRole("Administrator"))
            {
                <th>
                    @Html.DisplayNameFor(model => model.Seller)
                </th>
            }
        }


        <th>Actions</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Classification)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Region)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastPurchase)
            </td>

            @{
                if (User.IsInRole("Administrator"))
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.Seller)
                    </td>
                }
            }

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
                }

</table>